export const ALL_NAV = [
  { path: '/', label: 'Dashboard', icon: '🏠', roles: ['admin', 'manager', 'employee', 'accountant'] },
  { path: '/users', label: 'User Management', icon: '👥', roles: ['admin'] },
  { path: '/employees-roster', label: 'Employees', icon: '👷', roles: ['admin', 'manager'] },
  { path: '/activities', label: 'All Activities', icon: '📋', roles: ['admin', 'manager'] },
  { path: '/my-activities', label: 'My Activities', icon: '✏️', roles: ['employee'] },
  { path: '/flocks', label: 'Flocks', icon: '🐔', roles: ['admin', 'manager', 'employee'] },
  { path: '/daily-log', label: 'Daily Log', icon: '📝', roles: ['admin', 'manager', 'employee'] },
  { path: '/expenses', label: 'Expenses', icon: '💸', roles: ['admin', 'accountant'] },
  { path: '/budgets', label: 'Budget Planning', icon: '📊', roles: ['admin', 'accountant'] },
  { path: '/wages', label: 'Wage Tracking', icon: '💰', roles: ['admin', 'accountant'] },
  { path: '/financial', label: 'Financial', icon: '💹', roles: ['admin', 'manager', 'accountant'] },
  { path: '/vaccinations', label: 'Vaccines', icon: '💉', roles: ['admin', 'manager', 'employee'] },
  { path: '/feed', label: 'Feed Costs', icon: '🌾', roles: ['admin', 'manager', 'employee', 'accountant'] },
  { path: '/sales', label: 'Sales', icon: '🛒', roles: ['admin', 'manager', 'accountant'] },
  { path: '/medicine', label: 'Medicine', icon: '💊', roles: ['admin', 'manager', 'employee', 'accountant'] },
  { path: '/fcr', label: 'FCR', icon: '📈', roles: ['admin', 'manager', 'employee'] },
  { path: '/profit', label: 'Profit/Loss', icon: '📉', roles: ['admin', 'manager', 'accountant'] },
  { path: '/compliance', label: 'PDF Report', icon: '📄', roles: ['admin', 'accountant'] },
  { path: '/whatsapp', label: 'WhatsApp', icon: '💬', roles: ['admin', 'manager'] },
  { path: '/incubation', label: 'Incubation', icon: '🐣', roles: ['admin', 'manager', 'employee'] },
  { path: '/vet-notes', label: 'Vet Notes', icon: '🩺', roles: ['admin', 'manager', 'employee'] },
  { path: '/pasture', label: 'Pasture', icon: '🌿', roles: ['admin', 'manager', 'employee'] },
  { path: '/resources', label: 'Energy & Water', icon: '⚡', roles: ['admin', 'manager', 'employee', 'accountant'] },
  { path: '/settings', label: 'Settings', icon: '⚙️', roles: ['admin'] },
]

export const PAGE_TITLES = {
  '/': 'Dashboard',
  '/users': 'User Management',
  '/employees-roster': 'Employees',
  '/activities': 'All Activities',
  '/my-activities': 'My Activities',
  '/flocks': 'Flock Manager',
  '/daily-log': 'Daily Log',
  '/expenses': 'Expense Tracking',
  '/budgets': 'Budget Planning',
  '/wages': 'Wage Tracking',
  '/financial': 'Financial Overview',
  '/vaccinations': 'Vaccination Reminders',
  '/feed': 'Feed Cost Tracker',
  '/sales': 'Sales Log',
  '/medicine': 'Medicine Log',
  '/fcr': 'FCR Calculator',
  '/profit': 'Profit & Loss',
  '/compliance': 'Compliance Report',
  '/whatsapp': 'WhatsApp Alerts',
  '/incubation': 'Hatchery & Incubation',
  '/vet-notes': 'Vet & Advisor Notes',
  '/pasture': 'Pasture & Free-Range',
  '/resources': 'Energy & Water Monitor',
  '/settings': 'System Settings',
}
